name: 'pod-diff-action'
description: 'View outdated cocoapods'
author: 'Cody LeBlanc'
inputs:
  custom_update_cmd:
    description: 'custom command to run for updating pods'
    required: false
    default: 'pod update'
runs:
  using: 'node12'
  main: 'dist/index.js'
