name: 'pod-diff-action'
description: 'View outdated cocoapods'
author: 'Cody LeBlanc'
inputs:
  update_cmd:
    description: 'custom command to run for updating pods'
    required: false
    default: 'pod update'
  working_dir:
    description: 'custom directory that includes the Podfile.lock'
    required: false
    default: './'
  token:
    description: 'token to use to authenticate with GitHub'
    required: true
  base_branch:
    description: 'current base branch checked out'
    required: true
  pr_title:
    description: 'the title of the pull request'
    required: false
    default: 'Cocoapod Dependency Update 📦'
  commit_email:
    description: 'email to use when committing the lockfile update'
    required: true
  commit_username:
    description: 'username to use when committing the lockfile update'
    required: true
  commit_message:
    description: 'the commit message to use when commiting the update'
    required: false
    default: 'Update cocoapods'
runs:
  using: 'node12'
  main: 'dist/index.js'
